### ISSUE TITLE
UnboundLocalError when running digit_recognizer.py

### ISSUE THREAD

**Issue by Razvan4Madrid** [fractalbass/speech_recognition#1]
I got the following error message: 

UnboundLocalError                         Traceback (most recent call last)
~/library/digit_recognizer.py in <module>
     72 if __name__ == "__main__":
     73     dr = digit_recognizer()
---> 74     dr.run()

~/library/digit_recognizer.py in run(self)
     48                     label = item['label']
     49
---> 50             print("Filename: {0},  Digit: {1}".format(filename, label))
     51
     52         print("Done.")

UnboundLocalError: local variable 'label' referenced before assignment

I think this originates in the fact that the digit_directory from the (def process_directory ) has other subdirectories with the number names  zero to ten instead of having the raw wav files in them.
I think this line could cause the problem:    for filename in [x for x in os.listdir(self.digit_directory) if x.endswith('.wav')]:

**Comment by fractalbass** [comment]
Hi Razvan,

Thanks for taking the time to download and try out the code.  I took a look at this code (it has been several years since I wrote it).  For the speech_recognition.py program, I was able to get that to work right away.  Here is what I did...

1.  Cloned the repo to my mac.
2.  Created a virtual conda environment with python 3.6.10
3.  Installed the (newly added) requirements.txt file (pip install -r requirements.txt)
4.  Ran python speech_recognition.py

As for the digit_recognizer.py, you are correct that there was a bug related to the structure of the data.  Also, some of the .WAV files where not constructed very well.  I tried to address these problems.  Please see if you can get the latest version of the code.  Here is a quick summary of what I did:

There was some very bad (old) python in there for getting the names of the files.  I modified the code to use "glob" instead.  I also renamed some of the variables and classes to try and make things a bit more clear.  Unfortunately, this implementation of MFCC doesn't work that well.  In fact, I am not sure, but I think the digit recognizer misses on every single digit.  Perhaps you can make it better?

Thanks again, and good luck!

Miles Porter

ps.  I think the the "state of the art" on this stuff is now to generate a sort of sonogram of the sounds using a Fourier transform.  From there you can apply a convolutional neural network on that "image".  Here is an article that sort of talks about the approach:  https://towardsdatascience.com/audio-processing-in-tensorflow-208f1a4103aa

You can probably find even better articles if you google convolutional neural network sound recognition

Good Luck!

Miles
